name: ci

on:
  workflow_dispatch:
    inputs:
      latest:
        description: 'Indicator of whether or not is a prerelease'
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout upstream repo
        with:
          submodules: "recursive"
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cd upstream
          sed -i "s/http:\/\/ftp6284928.host108.abeiyun.cn/https:\/\/cdn.jsdelivr.net\/gh\/yes8080\/TVBox@main/g" `grep -rl "http:\/\/ftp6284928.host108.abeiyun.cn" ./`
          rm README.md
          cd ../
          cp -rf upstream/* .
          git commit -m "generated"
          git push 
